#!/usr/bin/env python3
"""Render the frozen Unicode tables into the Stage 7 migration.

The tables themselves live in ``sync-contract/unicode/`` as contract assets.
This script only formats them as SQL; it derives nothing.

That direction is deliberate. This script used to read the host CPython's
``unicodedata``, which meant the migration's contents depended on which Python
happened to run it — pinned by an interpreter version check that would simply
refuse to run anywhere else. Three implementations now have to agree on these
tables byte for byte (Postgres, the Windows client, the iPad client), so the
tables are the origin and every consumer is generated from them.

Each asset carries a canonical SHA-256. This script verifies it before writing
anything, so a table damaged in transit cannot reach the migration. That is not
hypothetical: the baseline table first arrived over a Windows transfer with
CRLF line endings and its digest did not match until the CR bytes were stripped.

Usage:
    generate_casefold_sql.py                      print the two generated blocks
    generate_casefold_sql.py --rewrite MIGRATION  splice them into a migration
    generate_casefold_sql.py --check MIGRATION    verify a migration matches
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ASSET_DIR = REPO_ROOT / "sync-contract" / "unicode"
CASEFOLD_ASSET = ASSET_DIR / "casefold-15.0.0.json"
ASSIGNED_ASSET = ASSET_DIR / "assigned-15.0.0.json"

ASSIGNED_BEGIN_MARKER = "-- BEGIN GENERATED UNICODE 15.0.0 ASSIGNED RANGES"
ASSIGNED_END_MARKER = "-- END GENERATED UNICODE 15.0.0 ASSIGNED RANGES"
CASEFOLD_BEGIN_MARKER = "-- BEGIN GENERATED UNICODE 15.0.0 FULL DEFAULT CASEFOLD"
CASEFOLD_END_MARKER = "-- END GENERATED UNICODE 15.0.0 FULL DEFAULT CASEFOLD"


def sql_text(value: str) -> str:
    return " || ".join(f"pg_catalog.chr({ord(char)})" for char in value)


def load_asset(path: Path) -> dict:
    asset = json.loads(path.read_text(encoding="utf-8"))
    if "\r" in path.read_text(encoding="utf-8"):
        raise SystemExit(f"{path.name}: contains CR. Assets are LF only.")
    return asset


def assigned_ranges() -> list[tuple[int, int]]:
    """Unicode 15.0.0 assigned ranges, verified against the asset digest."""
    asset = load_asset(ASSIGNED_ASSET)
    ranges = [(int(start), int(end)) for start, end in asset["ranges"]]
    canonical = "\n".join(f"{start:X}..{end:X}" for start, end in ranges)
    digest = hashlib.sha256(canonical.encode()).hexdigest()
    if digest != asset["canonical_sha256"]:
        raise SystemExit(
            f"{ASSIGNED_ASSET.name}: canonical digest mismatch\n"
            f"  expected {asset['canonical_sha256']}\n  got      {digest}"
        )
    if len(ranges) != asset["range_count"]:
        raise SystemExit(f"{ASSIGNED_ASSET.name}: range_count disagrees with ranges")
    return ranges


def casefold_mappings() -> list[tuple[int, str]]:
    """Unicode 15.0.0 full default case folding, verified against the asset digest."""
    asset = load_asset(CASEFOLD_ASSET)
    mappings = [
        (int(source, 16), "".join(chr(int(piece, 16)) for piece in folded))
        for source, folded in asset["mappings"].items()
    ]
    mappings.sort()
    canonical = ";".join(
        f"{source:X}>{','.join(f'{ord(char):X}' for char in folded)}"
        for source, folded in mappings
    )
    digest = hashlib.sha256(canonical.encode()).hexdigest()
    if digest != asset["canonical_sha256"]:
        raise SystemExit(
            f"{CASEFOLD_ASSET.name}: canonical digest mismatch\n"
            f"  expected {asset['canonical_sha256']}\n  got      {digest}"
        )
    if len(mappings) != asset["mapping_count"]:
        raise SystemExit(f"{CASEFOLD_ASSET.name}: mapping_count disagrees with mappings")
    return mappings


def render_assigned_sql() -> str:
    ranges = assigned_ranges()
    lines = [
        ASSIGNED_BEGIN_MARKER,
        "-- Generated by supabase/scripts/generate_casefold_sql.py.",
    ]
    for offset in range(0, len(ranges), 400):
        chunk = ranges[offset : offset + 400]
        lines.append("insert into private.unicode15_assigned_ranges (range_start, range_end) values")
        lines.append(",\n".join(f"  ({start}, {end})" for start, end in chunk))
        lines.append("on conflict (range_start) do nothing;")
    lines.extend([ASSIGNED_END_MARKER, f"-- assigned_range_count: {len(ranges)}"])
    return "\n".join(lines)


def render_casefold_sql() -> str:
    mappings = casefold_mappings()
    lines = [CASEFOLD_BEGIN_MARKER, "-- Generated by supabase/scripts/generate_casefold_sql.py."]
    for offset in range(0, len(mappings), 400):
        chunk = mappings[offset : offset + 400]
        lines.append("insert into private.unicode15_casefold (source_codepoint, mapping) values")
        rows = [f"  ({source}, {sql_text(mapping)})" for source, mapping in chunk]
        lines.append(",\n".join(rows))
        lines.append("on conflict (source_codepoint) do nothing;")
    lines.extend([CASEFOLD_END_MARKER, f"-- mapping_count: {len(mappings)}"])
    return "\n".join(lines)


def replace_generated_block(source: str, begin_marker: str, end_marker: str, generated: str) -> str:
    begin = source.index(begin_marker)
    end = source.index(end_marker, begin) + len(end_marker)
    line_end = source.find("\n", end)
    if line_end < 0:
        line_end = len(source)
    count_line_end = source.find("\n", line_end + 1)
    if source[line_end + 1 :].startswith(("-- mapping_count:", "-- assigned_range_count:")):
        line_end = len(source) if count_line_end < 0 else count_line_end
    return source[:begin] + generated + source[line_end:]


def splice(source: str) -> str:
    source = replace_generated_block(
        source, ASSIGNED_BEGIN_MARKER, ASSIGNED_END_MARKER, render_assigned_sql()
    )
    return replace_generated_block(
        source, CASEFOLD_BEGIN_MARKER, CASEFOLD_END_MARKER, render_casefold_sql()
    )


def main() -> None:
    if len(sys.argv) == 3 and sys.argv[1] in ("--rewrite", "--check"):
        path = Path(sys.argv[2])
        source = path.read_text(encoding="utf-8")
        rendered = splice(source)
        if sys.argv[1] == "--check":
            if rendered != source:
                raise SystemExit(f"{path}: generated blocks differ from the assets")
            print(f"{path}: generated blocks match the contract assets byte for byte")
            return
        path.write_text(rendered, encoding="utf-8")
        print(f"rewrote {path} from {ASSET_DIR}")
        return
    if len(sys.argv) != 1:
        raise SystemExit(
            "usage: generate_casefold_sql.py [--rewrite MIGRATION.sql | --check MIGRATION.sql]"
        )
    print(render_assigned_sql())
    print(render_casefold_sql())


if __name__ == "__main__":
    main()
