#!/usr/bin/env python3
"""Generate the immutable Unicode 15.0.0 full default case-fold table.

The generated rows are vendored into the Stage 7 migration so the database
does not depend on its locale or on a server-specific ICU version. Run this
script only with Python 3.12.13 / Unicode data 15.0.0.
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path


EXPECTED_PYTHON = (3, 12, 13)
EXPECTED_UNICODE = "15.0.0"


def sql_text(value: str) -> str:
    return " || ".join(f"pg_catalog.chr({ord(char)})" for char in value)


ASSIGNED_BEGIN_MARKER = "-- BEGIN GENERATED UNICODE 15.0.0 ASSIGNED RANGES"
ASSIGNED_END_MARKER = "-- END GENERATED UNICODE 15.0.0 ASSIGNED RANGES"
CASEFOLD_BEGIN_MARKER = "-- BEGIN GENERATED UNICODE 15.0.0 FULL DEFAULT CASEFOLD"
CASEFOLD_END_MARKER = "-- END GENERATED UNICODE 15.0.0 FULL DEFAULT CASEFOLD"


def assigned_ranges() -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    previous: int | None = None
    for codepoint in range(sys.maxunicode + 1):
        assigned = unicodedata.category(chr(codepoint)) != "Cn"
        if assigned and start is None:
            start = previous = codepoint
        elif assigned:
            previous = codepoint
        elif start is not None and previous is not None:
            ranges.append((start, previous))
            start = previous = None
    if start is not None and previous is not None:
        ranges.append((start, previous))
    return ranges


def render_assigned_sql() -> str:
    ranges = assigned_ranges()
    lines = [
        ASSIGNED_BEGIN_MARKER,
        "-- Generated by supabase/scripts/generate_casefold_sql.py.",
    ]
    for offset in range(0, len(ranges), 400):
        chunk = ranges[offset : offset + 400]
        lines.append("insert into private.unicode15_assigned_ranges (range_start, range_end) values")
        lines.append(",\n".join(f"  ({start}, {end})" for start, end in chunk))
        lines.append("on conflict (range_start) do nothing;")
    lines.extend([ASSIGNED_END_MARKER, f"-- assigned_range_count: {len(ranges)}"])
    return "\n".join(lines)


def render_casefold_sql() -> str:
    mappings = [
        (codepoint, folded)
        for codepoint in range(sys.maxunicode + 1)
        if (folded := chr(codepoint).casefold()) != chr(codepoint)
    ]
    lines = [CASEFOLD_BEGIN_MARKER, "-- Generated by supabase/scripts/generate_casefold_sql.py."]
    for offset in range(0, len(mappings), 400):
        chunk = mappings[offset : offset + 400]
        lines.append("insert into private.unicode15_casefold (source_codepoint, mapping) values")
        rows = [f"  ({source}, {sql_text(mapping)})" for source, mapping in chunk]
        lines.append(",\n".join(rows))
        lines.append("on conflict (source_codepoint) do nothing;")
    lines.extend([CASEFOLD_END_MARKER, f"-- mapping_count: {len(mappings)}"])
    return "\n".join(lines)


def replace_generated_block(source: str, begin_marker: str, end_marker: str, generated: str) -> str:
    begin = source.index(begin_marker)
    end = source.index(end_marker, begin) + len(end_marker)
    line_end = source.find("\n", end)
    if line_end < 0:
        line_end = len(source)
    count_line_end = source.find("\n", line_end + 1)
    if source[line_end + 1 :].startswith(("-- mapping_count:", "-- assigned_range_count:")):
        line_end = len(source) if count_line_end < 0 else count_line_end
    return source[:begin] + generated + source[line_end:]


def main() -> None:
    if sys.version_info[:3] != EXPECTED_PYTHON:
        raise SystemExit(
            f"Python {EXPECTED_PYTHON!r} required, got {sys.version_info[:3]!r}"
        )
    if unicodedata.unidata_version != EXPECTED_UNICODE:
        raise SystemExit(
            f"Unicode {EXPECTED_UNICODE} required, got {unicodedata.unidata_version}"
        )

    assigned = render_assigned_sql()
    casefold = render_casefold_sql()
    if len(sys.argv) == 3 and sys.argv[1] == "--rewrite":
        path = Path(sys.argv[2])
        source = path.read_text(encoding="utf-8")
        source = replace_generated_block(
            source, ASSIGNED_BEGIN_MARKER, ASSIGNED_END_MARKER, assigned
        )
        source = replace_generated_block(
            source, CASEFOLD_BEGIN_MARKER, CASEFOLD_END_MARKER, casefold
        )
        path.write_text(source, encoding="utf-8")
        print(f"rewrote {path} with Unicode {EXPECTED_UNICODE} case-fold rows")
        return
    if len(sys.argv) != 1:
        raise SystemExit("usage: generate_casefold_sql.py [--rewrite MIGRATION.sql]")
    print(assigned)
    print(casefold)


if __name__ == "__main__":
    main()
