#!/usr/bin/env python3
"""Render server Unicode SQL only from the released contract assets.

The historical Stage 7 migration is immutable. ``--check`` proves that its
generated Unicode 15.0.0 blocks still match the frozen JSON assets and that the
whole migration retains its reviewed SHA-256. ``--rewrite-v2`` writes only the
marked data blocks in a newly-created storage-name-v2 migration.

Canonical combining class is intentionally not a frozen contract asset. The
contract leaves platform NFKC and CCC bounded by its pre/post checks, so the
PostgreSQL implementation materializes the nonzero-CCC set with the same
Python 3.12.13 / Unicode 15.0.0 toolchain already used by server CI. Scalars
outside the frozen Unicode 14.0.0 input baseline are filtered out first.
"""

from __future__ import annotations

import hashlib
import json
import sys
import unicodedata
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
UNICODE_DIR = ROOT / "sync-contract" / "unicode"

EXPECTED_PYTHON = (3, 12, 13)
EXPECTED_UNICODE = "15.0.0"
EXPECTED_HISTORICAL_MIGRATION_SHA256 = (
    "5374b61f270541ae3f40717269c82e3f60949889254d1cdaaaee94ffa99aa70d"
)

ASSET_DIGESTS = {
    "assigned-baseline-14.0.0.json": (
        "aed4e530cc5e0de638310db961f17f174d605282764a6657afd0f70e5515c85c"
    ),
    "assigned-15.0.0.json": (
        "5a354149c4f2b58f7c2ffc5eab9fc92f6eab5a68292ebce626f4ba402f736e31"
    ),
    "casefold-15.0.0.json": (
        "eac289d0d721c58867acb07af38d9a8e8ee374d328b33d93251ae6348e258439"
    ),
    "excluded-scalars.json": (
        "f56ee73bca1690e842a189336ffdfabe7625128f7f314a7ac567755952571e86"
    ),
}

ASSIGNED_BEGIN_MARKER = "-- BEGIN GENERATED UNICODE 15.0.0 ASSIGNED RANGES"
ASSIGNED_END_MARKER = "-- END GENERATED UNICODE 15.0.0 ASSIGNED RANGES"
CASEFOLD_BEGIN_MARKER = "-- BEGIN GENERATED UNICODE 15.0.0 FULL DEFAULT CASEFOLD"
CASEFOLD_END_MARKER = "-- END GENERATED UNICODE 15.0.0 FULL DEFAULT CASEFOLD"

V2_BASELINE_BEGIN_MARKER = "-- BEGIN GENERATED STORAGE-NAME-V2 ASSIGNED BASELINE 14.0.0"
V2_BASELINE_END_MARKER = "-- END GENERATED STORAGE-NAME-V2 ASSIGNED BASELINE 14.0.0"
V2_EXCLUDED_BEGIN_MARKER = "-- BEGIN GENERATED STORAGE-NAME-V2 EXCLUDED SCALARS"
V2_EXCLUDED_END_MARKER = "-- END GENERATED STORAGE-NAME-V2 EXCLUDED SCALARS"
V2_CASEFOLD_BEGIN_MARKER = "-- BEGIN GENERATED STORAGE-NAME-V2 FULL DEFAULT CASEFOLD"
V2_CASEFOLD_END_MARKER = "-- END GENERATED STORAGE-NAME-V2 FULL DEFAULT CASEFOLD"
V2_CCC_BEGIN_MARKER = "-- BEGIN GENERATED STORAGE-NAME-V2 NONZERO CCC"
V2_CCC_END_MARKER = "-- END GENERATED STORAGE-NAME-V2 NONZERO CCC"


def fail(message: str) -> None:
    raise SystemExit(message)


def load_asset(name: str) -> dict[str, Any]:
    path = UNICODE_DIR / name
    raw = path.read_bytes()
    if b"\r" in raw:
        fail(f"{path}: CR byte is forbidden")
    table = json.loads(raw.decode("utf-8"))
    expected = ASSET_DIGESTS[name]
    actual = canonical_asset_digest(table)
    if table.get("canonical_sha256") != expected or actual != expected:
        fail(f"{path}: canonical digest mismatch")
    return table


def range_pairs(table: dict[str, Any]) -> list[tuple[int, int]]:
    pairs: list[tuple[int, int]] = []
    for item in table["ranges"]:
        if isinstance(item, list):
            pairs.append((int(item[0]), int(item[1])))
        else:
            pairs.append((int(item["start"]), int(item["end"])))
    if len(pairs) != table["range_count"]:
        fail(f"{table.get('table_id')}: range_count mismatch")
    if sum(end - start + 1 for start, end in pairs) != table["scalar_count"]:
        fail(f"{table.get('table_id')}: scalar_count mismatch")
    return pairs


def canonical_asset_digest(table: dict[str, Any]) -> str:
    if "mappings" in table:
        entries = [
            f"{source.upper()}>{','.join(target.upper() for target in targets)}"
            for source, targets in sorted(
                table["mappings"].items(), key=lambda item: int(item[0], 16)
            )
        ]
        if len(entries) != table["mapping_count"]:
            fail(f"{table.get('table_id')}: mapping_count mismatch")
        canonical = ";".join(entries)
    else:
        canonical = "\n".join(
            f"{start:X}..{end:X}" for start, end in range_pairs(table)
        )
    return hashlib.sha256(canonical.encode("ascii")).hexdigest()


def sql_text(codepoints: list[int]) -> str:
    return " || ".join(f"pg_catalog.chr({codepoint})" for codepoint in codepoints)


def render_ranges_sql(
    table: dict[str, Any], target: str, begin_marker: str, end_marker: str,
    count_label: str,
) -> str:
    pairs = range_pairs(table)
    lines = [begin_marker, "-- Generated by supabase/scripts/generate_casefold_sql.py."]
    for offset in range(0, len(pairs), 400):
        chunk = pairs[offset : offset + 400]
        lines.append(f"insert into {target} (range_start, range_end) values")
        lines.append(",\n".join(f"  ({start}, {end})" for start, end in chunk))
        lines.append("on conflict (range_start) do nothing;")
    lines.extend([end_marker, f"-- {count_label}: {len(pairs)}"])
    return "\n".join(lines)


def render_casefold_sql(
    table: dict[str, Any], target: str, begin_marker: str, end_marker: str,
) -> str:
    mappings = [
        (int(source, 16), [int(target_hex, 16) for target_hex in targets])
        for source, targets in sorted(
            table["mappings"].items(), key=lambda item: int(item[0], 16)
        )
    ]
    lines = [begin_marker, "-- Generated by supabase/scripts/generate_casefold_sql.py."]
    for offset in range(0, len(mappings), 400):
        chunk = mappings[offset : offset + 400]
        lines.append(f"insert into {target} (source_codepoint, mapping) values")
        lines.append(",\n".join(
            f"  ({source}, {sql_text(targets)})" for source, targets in chunk
        ))
        lines.append("on conflict (source_codepoint) do nothing;")
    lines.extend([end_marker, f"-- mapping_count: {len(mappings)}"])
    return "\n".join(lines)


def render_nonzero_ccc_sql(baseline: dict[str, Any]) -> str:
    if sys.version_info[:3] != EXPECTED_PYTHON:
        fail(f"Python {EXPECTED_PYTHON!r} required, got {sys.version_info[:3]!r}")
    if unicodedata.unidata_version != EXPECTED_UNICODE:
        fail(f"Unicode {EXPECTED_UNICODE} required, got {unicodedata.unidata_version}")
    pairs = range_pairs(baseline)
    scalars = [
        scalar
        for start, end in pairs
        for scalar in range(start, end + 1)
        if unicodedata.combining(chr(scalar)) != 0
    ]
    canonical = "\n".join(f"{scalar:X}" for scalar in scalars).encode("ascii")
    digest = hashlib.sha256(canonical).hexdigest()
    lines = [
        V2_CCC_BEGIN_MARKER,
        "-- Generated from Python 3.12.13 / Unicode 15.0.0 after filtering",
        "-- through the frozen Unicode 14.0.0 assigned baseline.",
    ]
    for offset in range(0, len(scalars), 400):
        chunk = scalars[offset : offset + 400]
        lines.append("insert into private.storage_name_v2_nonzero_ccc (codepoint) values")
        lines.append(",\n".join(f"  ({scalar})" for scalar in chunk))
        lines.append("on conflict (codepoint) do nothing;")
    lines.extend([
        V2_CCC_END_MARKER,
        f"-- nonzero_ccc_count: {len(scalars)}",
        f"-- nonzero_ccc_sha256: {digest}",
    ])
    return "\n".join(lines)


def generated_blocks() -> tuple[dict[str, str], dict[str, str]]:
    assigned15 = load_asset("assigned-15.0.0.json")
    baseline14 = load_asset("assigned-baseline-14.0.0.json")
    excluded = load_asset("excluded-scalars.json")
    casefold = load_asset("casefold-15.0.0.json")
    historical = {
        ASSIGNED_BEGIN_MARKER: render_ranges_sql(
            assigned15, "private.unicode15_assigned_ranges",
            ASSIGNED_BEGIN_MARKER, ASSIGNED_END_MARKER, "assigned_range_count",
        ),
        CASEFOLD_BEGIN_MARKER: render_casefold_sql(
            casefold, "private.unicode15_casefold",
            CASEFOLD_BEGIN_MARKER, CASEFOLD_END_MARKER,
        ),
    }
    v2 = {
        V2_BASELINE_BEGIN_MARKER: render_ranges_sql(
            baseline14, "private.storage_name_v2_assigned_ranges",
            V2_BASELINE_BEGIN_MARKER, V2_BASELINE_END_MARKER, "assigned_range_count",
        ),
        V2_EXCLUDED_BEGIN_MARKER: render_ranges_sql(
            excluded, "private.storage_name_v2_excluded_ranges",
            V2_EXCLUDED_BEGIN_MARKER, V2_EXCLUDED_END_MARKER, "excluded_range_count",
        ),
        V2_CASEFOLD_BEGIN_MARKER: render_casefold_sql(
            casefold, "private.storage_name_v2_casefold",
            V2_CASEFOLD_BEGIN_MARKER, V2_CASEFOLD_END_MARKER,
        ),
        V2_CCC_BEGIN_MARKER: render_nonzero_ccc_sql(baseline14),
    }
    return historical, v2


def block_end(source: str, begin_marker: str) -> int:
    marker_to_end = {
        ASSIGNED_BEGIN_MARKER: (ASSIGNED_END_MARKER, 1),
        CASEFOLD_BEGIN_MARKER: (CASEFOLD_END_MARKER, 1),
        V2_BASELINE_BEGIN_MARKER: (V2_BASELINE_END_MARKER, 1),
        V2_EXCLUDED_BEGIN_MARKER: (V2_EXCLUDED_END_MARKER, 1),
        V2_CASEFOLD_BEGIN_MARKER: (V2_CASEFOLD_END_MARKER, 1),
        V2_CCC_BEGIN_MARKER: (V2_CCC_END_MARKER, 2),
    }
    end_marker, following_lines = marker_to_end[begin_marker]
    end = source.index(end_marker, source.index(begin_marker)) + len(end_marker)
    for _ in range(following_lines):
        newline = source.find("\n", end)
        end = len(source) if newline < 0 else newline
        if end == len(source):
            break
        end += 1
        next_newline = source.find("\n", end)
        end = len(source) if next_newline < 0 else next_newline
    return end


def extract_block(source: str, begin_marker: str) -> str:
    begin = source.index(begin_marker)
    return source[begin:block_end(source, begin_marker)]


def replace_blocks(source: str, blocks: dict[str, str]) -> str:
    for begin_marker, generated in blocks.items():
        begin = source.index(begin_marker)
        end = block_end(source, begin_marker)
        source = source[:begin] + generated + source[end:]
    return source


def check_blocks(path: Path, blocks: dict[str, str]) -> None:
    raw = path.read_bytes()
    if b"\r" in raw:
        fail(f"{path}: CR byte is forbidden")
    source = raw.decode("utf-8")
    for marker, generated in blocks.items():
        if extract_block(source, marker) != generated:
            fail(f"{path}: generated block differs: {marker}")


def main() -> None:
    historical, v2 = generated_blocks()
    if len(sys.argv) == 3 and sys.argv[1] == "--check":
        path = Path(sys.argv[2])
        check_blocks(path, historical)
        actual_sha = hashlib.sha256(path.read_bytes()).hexdigest()
        if actual_sha != EXPECTED_HISTORICAL_MIGRATION_SHA256:
            fail(f"{path}: historical migration SHA-256 changed: {actual_sha}")
        print(f"checked immutable historical migration: {actual_sha}")
        return
    if len(sys.argv) == 3 and sys.argv[1] in {"--rewrite-v2", "--check-v2"}:
        path = Path(sys.argv[2])
        if sys.argv[1] == "--rewrite-v2":
            source = path.read_text(encoding="utf-8")
            path.write_text(replace_blocks(source, v2), encoding="utf-8")
            print(f"rewrote storage-name-v2 generated blocks in {path}")
        check_blocks(path, v2)
        print(f"checked storage-name-v2 generated blocks in {path}")
        return
    fail(
        "usage: generate_casefold_sql.py "
        "(--check HISTORICAL.sql | --rewrite-v2 MIGRATION.sql | --check-v2 MIGRATION.sql)"
    )


if __name__ == "__main__":
    main()
