"""Generate/check iPad's frozen v2 lookup tables; never consult host Unicode."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "WriterPad/Sync/SyncV2StorageNameTables.swift"


def generate():
    casefold = json.loads((ROOT / "sync-contract/unicode/casefold-15.0.0.json").read_text(encoding="utf-8"))
    folded = ";".join(f"{src}>{','.join(dst)}" for src, dst in sorted(casefold["mappings"].items(), key=lambda row: int(row[0], 16)))
    assert hashlib.sha256(folded.encode()).hexdigest() == "eac289d0d721c58867acb07af38d9a8e8ee374d328b33d93251ae6348e258439"
    swift = (ROOT / "WriterPad/Sync/SyncV2UnicodeCasefold.swift").read_text(encoding="utf-8")
    packed_casefold = swift.split("private static let packed: String = [", 1)[1].split("]", 1)[0]
    assert "".join(re.findall(r'"([0-9A-F>,;]+)"', packed_casefold)) == folded
    # Simulator tests embed the released vectors so they do not read host files.
    test = (ROOT / "WriterPadTests/SyncV2ContractTests.swift").read_text(encoding="utf-8")
    embedded = re.search(r'let fixture = #"""(.*?)"""#', test, re.S).group(1)
    assert json.loads(embedded) == json.loads((ROOT / "sync-contract/conformance_vectors/storage-name-v2.json").read_text(encoding="utf-8"))
    baseline = json.loads((ROOT / "sync-contract/unicode/assigned-baseline-14.0.0.json").read_text(encoding="utf-8"))
    ranges = baseline["ranges"]
    canonical = "\n".join(f"{a:X}..{b:X}" for a, b in ranges)
    assert hashlib.sha256(canonical.encode()).hexdigest() == "aed4e530cc5e0de638310db961f17f174d605282764a6657afd0f70e5515c85c"
    exclusions = json.loads((ROOT / "sync-contract/unicode/excluded-scalars.json").read_text(encoding="utf-8"))
    excluded = [(r["start"], r["end"]) for r in exclusions["ranges"]]
    exclusion_text = "\n".join(f"{a:X}..{b:X}" for a, b in excluded)
    assert hashlib.sha256(exclusion_text.encode()).hexdigest() == "f56ee73bca1690e842a189336ffdfabe7625128f7f314a7ac567755952571e86"
    excluded_swift = ", ".join(f"0x{a:X}...0x{b:X}" for a, b in excluded)
    sql = (ROOT / "supabase/migrations/20260813063251_sync_contract_0_3_0_storage_name_v2.sql").read_text(encoding="utf-8")
    chunks = re.findall(r"insert into private.storage_name_v2_nonzero_ccc \(codepoint\) values(.*?)on conflict", sql, re.S)
    ccc = [int(n) for chunk in chunks for n in re.findall(r"\((\d+)\)", chunk)]
    assert len(ccc) == len(set(ccc)) == 912
    ccc_text = "\n".join(f"{n:X}" for n in ccc)
    assert hashlib.sha256(ccc_text.encode()).hexdigest() == "7d5606ea74ca510262aecd8d9acb5c21d1cd872a01825d7f8edf1bd91b209be5"
    packed = " ".join(f"{a:X}-{b:X}" for a, b in ranges)
    ccc_packed = " ".join(f"{n:X}" for n in ccc)
    return f'''// Generated by Scripts/generate_ipad_storage_name_v2.py. Do not edit.
// Frozen Unicode 14 assigned baseline and the released server's nonzero CCC set.
enum SyncV2StorageNameTables {{
    static let excluded: [ClosedRange<UInt32>] = [{excluded_swift}]
    static let assignedSHA256 = "{baseline['canonical_sha256']}"
    static let nonzeroCCCSHA256 = "7d5606ea74ca510262aecd8d9acb5c21d1cd872a01825d7f8edf1bd91b209be5"
    static let assigned: [ClosedRange<UInt32>] = "{packed}".split(separator: " ").map {{
        let ends = $0.split(separator: "-").map {{ UInt32($0, radix: 16)! }}
        return ends[0]...ends[1]
    }}
    static let nonzeroCCC: Set<UInt32> = Set("{ccc_packed}".split(separator: " ").map {{ UInt32($0, radix: 16)! }})
    static func isAssigned(_ scalar: UInt32) -> Bool {{
        var low = 0, high = assigned.count
        while low < high {{
            let mid = (low + high) / 2, range = assigned[mid]
            if scalar < range.lowerBound {{ high = mid }}
            else if scalar > range.upperBound {{ low = mid + 1 }}
            else {{ return true }}
        }}
        return false
    }}
}}
'''


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        assert TARGET.read_text(encoding="utf-8") == expected, "Regenerate frozen iPad tables"
        print("iPad storage-name-v2 tables match frozen assets")
    else:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
